# CMake generated Testfile for 
# Source directory: C:/mumps/lapack-3.6.1/TESTING
# Build directory: C:/mumps/lapack-3.6.1/TESTING
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xlintsts_stest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xlintsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xlintsts_stest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xlintsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xlintsts_stest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xlintsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xlintsts_stest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xlintsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xlintsts_stest_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xlintstrfs_stest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xlintstrfs.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xlintstrfs_stest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xlintstrfs.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xlintstrfs_stest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xlintstrfs.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xlintstrfs_stest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xlintstrfs.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/stest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xlintstrfs_stest_rfp_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/snep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/snep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/snep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/snep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_nep_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sep_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_svd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sec_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sed_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sed.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sed.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sed_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sed.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sed.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sed_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sed.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sed.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sed_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sed.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sed.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sed_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sgg_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sgd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_ssb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_ssb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_ssb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_ssb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_ssb_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_ssg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_ssg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_ssg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_ssg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ssg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_ssg_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sbal_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sbak_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sgbal_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sgbak_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_sbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_sbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_sbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_sbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_sbb_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_glm_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_gqr_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/sgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_gsv_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/scsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/scsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/scsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/scsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_csd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtsts_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/slse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtsts_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/slse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtsts_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/slse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtsts_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtsts.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/slse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtsts_lse_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xlintstd_dtest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xlintstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xlintstd_dtest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xlintstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xlintstd_dtest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xlintstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xlintstd_dtest_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xlintstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xlintstd_dtest_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xlintstrfd_dtest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xlintstrfd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xlintstrfd_dtest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xlintstrfd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xlintstrfd_dtest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xlintstrfd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xlintstrfd_dtest_rfp_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xlintstrfd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dtest_rfp.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xlintstrfd_dtest_rfp_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dnep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dnep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dnep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_nep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/nep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dnep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_nep_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_sep_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/sep.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsep.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_sep_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_svd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/svd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsvd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_svd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dec_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dec.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dec.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dec_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_ded_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ded.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ded.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_ded_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ded.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ded.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_ded_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ded.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ded.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_ded_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/ded.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/ded.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_ded_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dgg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dgg_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dgd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dgd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dsb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dsb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dsb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dsb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dsb_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dsg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dsg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dsg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dsg_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dsg.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dsg_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dbal_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dbak_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dgbal_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbal.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dgbal_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dgbak_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgbak.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dgbak_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_dbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_dbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_dbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_dbb_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dbb.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_dbb_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_glm_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/glm.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dglm.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_glm_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_gqr_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gqr.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgqr.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_gqr_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_gsv_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/gsv.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dgsv.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_gsv_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dcsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dcsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dcsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_csd_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/csd.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dcsd.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_csd_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK-xeigtstd_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dlse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK-xeigtstd_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dlse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK-xeigtstd_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dlse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK-xeigtstd_lse_in "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xeigtstd.exe" "-DINPUT=C:/mumps/lapack-3.6.1/TESTING/lse.in" "-DOUTPUT=C:/mumps/lapack-3.6.1/TESTING/dlse.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(LAPACK-xeigtstd_lse_in NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(LAPACK_Test_Summary "C:/Python37/python.exe" "lapack_testing.py")
  set_tests_properties(LAPACK_Test_Summary PROPERTIES  WORKING_DIRECTORY "C:/mumps/lapack-3.6.1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(LAPACK_Test_Summary "C:/Python37/python.exe" "lapack_testing.py")
  set_tests_properties(LAPACK_Test_Summary PROPERTIES  WORKING_DIRECTORY "C:/mumps/lapack-3.6.1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(LAPACK_Test_Summary "C:/Python37/python.exe" "lapack_testing.py")
  set_tests_properties(LAPACK_Test_Summary PROPERTIES  WORKING_DIRECTORY "C:/mumps/lapack-3.6.1")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(LAPACK_Test_Summary "C:/Python37/python.exe" "lapack_testing.py")
  set_tests_properties(LAPACK_Test_Summary PROPERTIES  WORKING_DIRECTORY "C:/mumps/lapack-3.6.1")
else()
  add_test(LAPACK_Test_Summary NOT_AVAILABLE)
endif()
subdirs("MATGEN")
subdirs("LIN")
subdirs("EIG")
