# CMake generated Testfile for 
# Source directory: C:/mumps/lapack-3.6.1/CBLAS/testing
# Build directory: C:/mumps/lapack-3.6.1/CBLAS/testing
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xscblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xscblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xscblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xscblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xscblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xscblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xscblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xscblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xscblat1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xscblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xscblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xscblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xscblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xscblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xscblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xscblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xscblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xscblat2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xscblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xscblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xscblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xscblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xscblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xscblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xscblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xscblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/sin3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/stest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xscblat3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xdcblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xdcblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xdcblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xdcblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xdcblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xdcblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xdcblat1 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xdcblat1.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest1.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xdcblat1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xdcblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xdcblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xdcblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xdcblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xdcblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xdcblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xdcblat2 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xdcblat2.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din2" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest2.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xdcblat2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CBLAS-xdcblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Debug/xdcblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CBLAS-xdcblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/Release/xdcblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CBLAS-xdcblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/MinSizeRel/xdcblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CBLAS-xdcblat3 "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=C:/mumps/lapack-3.6.1/bin/RelWithDebInfo/xdcblat3.exe" "-DINPUT=C:/mumps/lapack-3.6.1/cblas/testing/din3" "-DOUTPUT=C:/mumps/lapack-3.6.1/cblas/testing/dtest3.out" "-DINTDIR=\$(Configuration)" "-P" "C:/mumps/lapack-3.6.1/TESTING/runtest.cmake")
else()
  add_test(CBLAS-xdcblat3 NOT_AVAILABLE)
endif()
